[build]
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"  # Versión de Node.js que estás usando
  TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"
  FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}" 
  FIREBASE_PRIVATE_KEY = "${FIREBASE_PRIVATE_KEY}"
  FIREBASE_CLIENT_EMAIL = "${FIREBASE_CLIENT_EMAIL}"
  FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
