# Configuración básica de Netlify
[build]
  # Carpeta donde Netlify busca archivos estáticos listos para servir
  publish = "public"

# Configuración de las funciones de Netlify
[functions]
  # Carpeta que contiene las funciones de Netlify
  directory = "netlify/functions"

# Rutas de redirección y reescritura
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de variables de entorno
[build.environment]
  NODE_VERSION = "20"  # Versión de Node.js que estás usando
  TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"
  FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}" 
  FIREBASE_PRIVATE_KEY = "${FIREBASE_PRIVATE_KEY}"
  FIREBASE_CLIENT_EMAIL = "${FIREBASE_CLIENT_EMAIL}"
  FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
